ECG_CATEGORIES = {
    "Rhythm Disorders": [
        "Ventricular tachycardia",
        "Bradycardia",
        "Brugada",
        "Wolff-Parkinson-White (Pre-excitation syndrome)",
        "Atrial flutter",
        "Ectopic atrial rhythm (< 100 BPM)",
        "Atrial tachycardia (>= 100 BPM)",
        "Sinusal",
        "Ventricular Rhythm",
        "Supraventricular tachycardia",
        "Junctional rhythm",
        "Regular",
        "Regularly irregular",
        "Irregularly irregular",
        "Afib",
        "Premature ventricular complex",
        "Premature atrial complex"
    ],
    "Conduction Disorder": [
        "Left anterior fascicular block",
        "Delta wave",
        "2nd degree AV block - mobitz 2",
        "Left bundle branch block",
        "Right bundle branch block",
        "Left axis deviation",
        "Atrial paced",
        "Right axis deviation",
        "Left posterior fascicular block",
        "1st degree AV block",
        "Right superior axis",
        "Nonspecific intraventricular conduction delay",
        "Third Degree AV Block",
        "2nd degree AV block - mobitz 1",
        "Prolonged QT",
        "U wave",
        "LV pacing",
        "Ventricular paced"
    ],
    "Enlargement of the heart chambers": [
        "Bi-atrial enlargement",
        "Left atrial enlargement",
        "Right atrial enlargement",
        "Left ventricular hypertrophy",
        "Right ventricular hypertrophy"
    ],
    "Pericarditis": [
        "Acute pericarditis"
    ],
    "Infarction or ischemia": [
        "Q wave (septal- V1-V2)",
        "ST elevation (anterior - V3-V4)",
        "Q wave (posterior - V7-V9)",
        "Q wave (inferior - II, III, aVF)",
        "Q wave (anterior - V3-V4)",
        "ST elevation (lateral - I, aVL, V5-V6)",
        "Q wave (lateral- I, aVL, V5-V6)",
        "ST depression (lateral - I, avL, V5-V6)",
        "Acute MI",
        "ST elevation (septal - V1-V2)",
        "ST elevation (inferior - II, III, aVF)",
        "ST elevation (posterior - V7-V8-V9)",
        "ST depression (inferior - II, III, aVF)",
        "ST depression (anterior - V3-V4)"
    ],
    "Other diagnoses": [
        "ST downslopping",
        "ST depression (septal- V1-V2)",
        "R/S ratio in V1-V2 >1",
        "RV1 + SV6 > 11 mm",
        "Polymorph",
        "rSR' in V1-V2",
        "QRS complex negative in III",
        "qRS in V5-V6-I, aVL",
        "QS complex in V1-V2-V3",
        "R complex in V5-V6",
        "RaVL > 11 mm",
        "T wave inversion (septal- V1-V2)",
        "SV1 + RV5 or RV6 > 35 mm",
        "T wave inversion (inferior - II, III, aVF)",
        "Monomorph",
        "T wave inversion (anterior - V3-V4)",
        "T wave inversion (lateral -I, aVL, V5-V6)",
        "Low voltage",
        "Lead misplacement",
        "ST depression (anterior - V3-V4)",
        "Early repolarization",
        "ST upslopping",
        "no_qrs"
    ]
}

ECG_PATTERNS = [
    "Sinusal",
    "Regular",
    "Monomorph",
    "QS complex in V1-V2-V3",
    "R complex in V5-V6",
    "T wave inversion (inferior - II, III, aVF)",
    "Left bundle branch block",
    "RaVL > 11 mm",
    "SV1 + RV5 or RV6 > 35 mm",
    "T wave inversion (lateral -I, aVL, V5-V6)",
    "T wave inversion (anterior - V3-V4)",
    "Left axis deviation",
    "Left ventricular hypertrophy",
    "Bradycardia",
    "Q wave (inferior - II, III, aVF)",
    "Afib",
    "Irregularly irregular",
    "Atrial tachycardia (>= 100 BPM)",
    "Nonspecific intraventricular conduction delay",
    "Premature ventricular complex",
    "Polymorph",
    "T wave inversion (septal- V1-V2)",
    "Right bundle branch block",
    "Ventricular paced",
    "ST elevation (anterior - V3-V4)",
    "ST elevation (septal - V1-V2)",
    "1st degree AV block",
    "Premature atrial complex",
    "Atrial flutter",
    "rSR' in V1-V2",
    "qRS in V5-V6-I, aVL",
    "Left anterior fascicular block",
    "Right axis deviation",
    "2nd degree AV block - mobitz 1",
    "ST depression (inferior - II, III, aVF)",
    "Acute pericarditis",
    "ST elevation (inferior - II, III, aVF)",
    "Low voltage",
    "Regularly irregular",
    "Junctional rhythm",
    "Left atrial enlargement",
    "ST elevation (lateral - I, aVL, V5-V6)",
    "Atrial paced",
    "Right ventricular hypertrophy",
    "Delta wave",
    "Wolff-Parkinson-White (Pre-excitation syndrome)",
    "Prolonged QT",
    "ST depression (anterior - V3-V4)",
    "QRS complex negative in III",
    "Q wave (lateral- I, aVL, V5-V6)",
    "Supraventricular tachycardia",
    "ST downslopping",
    "ST depression (lateral - I, avL, V5-V6)",
    "2nd degree AV block - mobitz 2",
    "U wave",
    "R/S ratio in V1-V2 >1",
    "RV1 + SV6 > 11 mm",
    "Left posterior fascicular block",
    "Right atrial enlargement",
    "ST depression (septal- V1-V2)",
    "Q wave (septal- V1-V2)",
    "Q wave (anterior - V3-V4)",
    "ST upslopping",
    "Right superior axis",
    "Ventricular tachycardia",
    "ST elevation (posterior - V7-V8-V9)",
    "Ectopic atrial rhythm (< 100 BPM)",
    "Lead misplacement",
    "Third Degree AV Block",
    "Acute MI",
    "Early repolarization",
    "Q wave (posterior - V7-V9)",
    "Bi-atrial enlargement",
    "LV pacing",
    "Brugada",
    "Ventricular Rhythm",
    "no_qrs"
]